import Head from 'next/head';
import { Box, Button } from '@mui/material';
import { useAuth } from '@/contexts/useAuth';
import { useEffect } from 'react';

export default function Home() {
  const { user, isLoading, login, logout } = useAuth();
  useEffect(() => {
    console.log(user);
    console.log('loading', isLoading);
  }, [user, isLoading, login, logout]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box component="main">
        <Button variant="contained" color="primary" onClick={login}>
          ログイン
        </Button>
        <Button variant="contained" color="primary" onClick={logout}>
          ログアウト
        </Button>
      </Box>
    </>
  );
}
