import Head from 'next/head';
import { Box } from '@mui/material';
import Top from '@/components/top';

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box component="main">
        <Top />
      </Box>
    </>
  );
}
